name: libddog tests
on: [push]
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: sudo apt-get install python3-venv
      - run: python -m venv ve
      - run: ve/bin/pip install -r dev-requirements.txt
      - run: ./unittests
        env:
          PATH: $PATH:ve/bin

  run-type-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: sudo apt-get install python3-venv
      - run: python -m venv ve
      - run: ve/bin/pip install -r dev-requirements.txt
      - run: ./check
        env:
          PATH: $PATH:ve/bin
